# Generated by Django 5.0.6 on 2026-06-24 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NDVIReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ndvi_value', models.FloatField()),
                ('image_url', models.URLField(blank=True)),
                ('health', models.CharField(default='good', max_length=20)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ndvi_readings', to='farms.farm')),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
    ]
