# Generated by Django 5.0.6 on 2026-06-24 13:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CarbonActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('practice', models.CharField(choices=[('cover_crop', 'Cover Cropping'), ('agroforestry', 'Agroforestry'), ('no_till', 'No-Till'), ('composting', 'Composting')], max_length=50)),
                ('area_hectares', models.FloatField()),
                ('estimated_tonnes', models.FloatField()),
                ('evidence_url', models.URLField(blank=True)),
                ('verified', models.BooleanField(default=False)),
                ('certificate_url', models.URLField(blank=True)),
                ('logged_at', models.DateTimeField(auto_now_add=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carbon_activities', to='farms.farm')),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
