# Generated by Django 5.0.6 on 2026-06-25 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0001_initial'),
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weatheralert',
            name='farm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='farms.farm'),
        ),
        migrations.AlterField(
            model_name='weatheralert',
            name='severity',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')]),
        ),
    ]
